name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: header, repositories, commits
          config_timezone: Europe/Berlin
          config_theme: tokyonight
          config_border: false
          output_action: pull-request
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: false
          languages: true
          languages_limit: 6
          config_timezone: Europe/Berlin
          config_theme: tokyonight
          config_border: false
          output_action: pull-request